import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./components/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Workout Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
    
      <body className={inter.className}>  
        <div className="flex overflow-y-hidden">
        <Menu/>
        <div className=" grow pt-9 pr-5 pl-3 overflow-y-scroll h-[99vh]">
        {children}
          </div>
        </div></body>
    </html>
  );
}
